name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 2 * * 0'
defaults:
  run:
    shell: bash
jobs:
  test:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.${{ matrix.java }}"
    - uses: coursier/cache-action@v5
    - run: sbt -v "+ test"
