name: CI
on:
  pull_request:
  push:
defaults:
  run:
    shell: bash
jobs:
  test:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: actions/setup-java@v4
      with:
        java-version: "${{ matrix.java }}"
        distribution: adopt
    - uses: coursier/cache-action@v5
    - run: sbt -v "+ test"
